# Generated by Django 2.2.25 on 2022-05-25 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nea_pathways', '0019_alter_courseprice_php'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePracticalDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('courseoverview', models.OneToOneField(default='course-v1:edX+DemoX+Demo_Course', on_delete=django.db.models.deletion.CASCADE, to='course_overviews.CourseOverview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormFillingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('practical_name', models.CharField(default='Practical', max_length=50)),
                ('practical_description', models.TextField(default='description of practical', max_length=250)),
                ('maximum_students', models.IntegerField(default=100, verbose_name='Maximum Students')),
                ('venue', models.TextField(default='venue of practical', max_length=250, verbose_name='Venue')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('courseoverview', models.ForeignKey(default='course-v1:edX+DemoX+Demo_Course', on_delete=django.db.models.deletion.CASCADE, to='HandsOnPractical.CoursePracticalDate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentConsultationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone_number', models.CharField(max_length=10)),
                ('other_requirements', models.TextField(blank=True, max_length=200)),
                ('other_comments', models.TextField(blank=True, max_length=200)),
                ('practical_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandsOnPractical.FormFillingDate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
